// Local SVG assets; provenance is recorded in public/logos/skills/SOURCES.md.
export const skillLogos: Record<string, string> = {
  "React Native": '/logos/skills/react.svg',
  "Java Swing": '/logos/skills/java.svg',
  "Expo": '/logos/skills/expo.svg',
  "WXT": '/logos/skills/wxt.svg',
  "XGBoost": '/logos/skills/xgboost.png',
  "SHAP": '/logos/skills/shap.png',
  "Gemini API": '/logos/skills/gemini.svg',
  "Auth0": '/logos/skills/auth0.svg',
  "Stripe": '/logos/skills/stripe.svg',
  "pytest": '/logos/skills/pytest.svg',
  "JUnit": '/logos/skills/junit.svg',
  "Maven": '/logos/skills/maven.svg',
  "Gradle": '/logos/skills/gradle.svg',
  "OpenCV": '/logos/skills/opencv.svg',
  "Python": '/logos/skills/python.svg',
  "Java": '/logos/skills/java.svg',
  "C": '/logos/skills/c.svg',
  "C++": '/logos/skills/cplusplus.svg',
  "TypeScript": '/logos/skills/typescript.svg',
  "JavaScript": '/logos/skills/javascript.svg',
  "Dart": '/logos/skills/dart.svg',
  "R": '/logos/skills/r.svg',
  "Bash": '/logos/skills/bash.svg',
  "PowerShell": '/logos/skills/powershell.svg',
  "HTML": '/logos/skills/html5.svg',
  "CSS": '/logos/skills/css3.svg',
  "React": '/logos/skills/react.svg',
  "Next.js": '/logos/skills/nextjs.svg',
  "Flutter": '/logos/skills/flutter.svg',
  "Node.js": '/logos/skills/nodejs.svg',
  "Express.js": '/logos/skills/express.svg',
  "FastAPI": '/logos/skills/fastapi.svg',
  "Flask": '/logos/skills/flask.svg',
  "Django": '/logos/skills/django.svg',
  "Tailwind CSS": '/logos/skills/tailwindcss.svg',
  "Sequelize": '/logos/skills/sequelize.svg',
  "D3.js": '/logos/skills/d3js.svg',
  "Pandas": '/logos/skills/pandas.svg',
  "NumPy": '/logos/skills/numpy.svg',
  "Scikit-learn": '/logos/skills/scikitlearn.svg',
  "TensorFlow": '/logos/skills/tensorflow.svg',
  "PyTorch": '/logos/skills/pytorch.svg',
  "Matplotlib": '/logos/skills/matplotlib.svg',
  "Spark": '/logos/skills/apachespark.svg',
  "PostgreSQL": '/logos/skills/postgresql.svg',
  "MySQL": '/logos/skills/mysql.svg',
  "SQLite": '/logos/skills/sqlite.svg',
  "Supabase": '/logos/skills/supabase.svg',
  "MongoDB": '/logos/skills/mongodb.svg',
  "AWS / EC2": '/logos/skills/amazonwebservices.svg',
  "Cloudflare": '/logos/skills/cloudflare.svg',
  "Docker": '/logos/skills/docker.svg',
  "GitHub Actions": '/logos/skills/githubactions.svg',
  "Git": '/logos/skills/git.svg',
  "GitHub": '/logos/skills/github.svg',
  "Vite": '/logos/skills/vite.svg',
  "VS Code": '/logos/skills/vscode.svg',
  "Jupyter": '/logos/skills/jupyter.svg',
  "Jira": '/logos/skills/jira.svg',
  "Figma": '/logos/skills/figma.svg',
  "Pydantic": '/logos/skills/pydantic.svg',
  "Hugging Face": '/logos/skills/huggingface.svg',
  "LangChain": '/logos/skills/langchain.svg',
  "LangGraph": '/logos/skills/langgraph.svg',
  "Snowflake": '/logos/skills/snowflake.svg',
  "Modal": '/logos/skills/modal.png',
  "Claude Code": '/logos/skills/claudecode.svg',
  "Cursor": '/logos/skills/cursor.svg',
  "Power BI": '/logos/skills/powerbi.svg',
  "Seaborn": '/logos/skills/seaborn.svg',
  "SQL": '/logos/skills/database.svg',
  "CI/CD": '/logos/skills/workflow.svg',
  "REST APIs": '/logos/skills/network.svg',
};
